version: "3.8"
services:
  nodeserver:
    build:
      context: ./app
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
  nodeserver2:
    build:
      context: ./app
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
  redis:
    restart: always
    build:
      context: ./redis
    ports:
      - "6379:6379"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
